const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/accounts': 'accounts',
  '/modules': 'modules',
  '/versions': 'versions',
  '/roles': 'Roles',
  '/profile': 'IoT Generator',
  '/notifications': 'Notifications',
  '/device': 'Devices',
  '/components': 'Components',
  '/fleet':'IoT fleet',
  '/device/data': 'data',
  "geofence": "geofence",
  '/charts': 'Charts',
  "/geof":'Geo fance',
  '/Users': 'Users',
  "/log":"Data Log",
  "/categories":"App Config",
  "/Notifications":"Notifications",
  '/qa/profileTable':'Profile Table',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Social Buttons',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/forms': 'Forms',
  '/forms/basic-forms': 'Basic Forms',
  '/forms/advanced-forms': 'Advanced Forms',
  '/editors': 'Editors',
  '/editors/text-editors': 'Text Editors',
  '/editors/code-editors': 'Code Editors',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/plugins': 'Plugins',
  '/plugins/calendar': 'Calendar',
  '/plugins/loading-buttons': 'Loading Buttons',
  '/plugins/notifications': 'Notifications',
  '/plugins/spinners': 'Spinners',
  '/widgets': 'Widgets',
  '/ui-kits': 'UI Kits',
  '/ui-kits/invoicing': 'Invoicing',
  '/ui-kits/invoicing/invoice': 'Invoice',
  '/ui-kits/email/compose': 'Compose',
  '/ui-kits/email/inbox': 'Inbox',
  '/ui-kits/email/message': 'Message'
 
};
export default routes;
